---
- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - tmux
        - nvim

  tasks:
    - name: Node tasks
      include_tasks: tasks/node.yml
      tags:
        - node

    - name: ZSH tasks
      include_tasks: tasks/zsh.yml
      tags:
        - zsh

    - name: TMUX tasks
      include_tasks: tasks/tmux.yml
      tags:
        - tmux
    - name: nvim tasks
      include_tasks: tasks/nvim.yml
      tags:
        - nvim
