- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
  tasks:
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/zsh.yml
