- name: Install nodejs and npm
  hosts: localhost
  tasks:
    - name: Install nodejs and npm
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
      tags:
        - node

- name: Install n globally
  hosts: localhost
  tasks:
    - name: Install n globally
      package:
        name: n
        state: present
      tags:
        - node
