- name: Install nodejs and npm
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm
  ignore_errors : true
  tags:
    - node

- name: Install n globally
  ignore_errors : true
  package:
    name: n
    state: present
  tags:
    - node
