---
    - name: Install prerequisites
      apt:
        name:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
        state: present

    - name: Clone Neovim repository using Ansible git module
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: '/tmp/neovim'
        depth: 1

    - name: Build and install Neovim
      command:
        cmd: "{{ item }}"
        chdir: /tmp/neovim
      loop:
        - make CMAKE_BUILD_TYPE=RelWithDebInfo
        - make install
