---
- name: Install prerequisites on macOS
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - ninja
    - cmake
    - gettext
    - curl
  when: ansible_system == 'Darwin'
  ignore_errors: true 
  tags:
    - nvim

- name: Install prerequisites on Linux
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ninja-build
    - gettext
    - cmake
    - unzip
    - curl
    - build-essential
  when: ansible_system == 'Linux'
  tags:
    - nvim

- name: Clone Neovim repository
  become: true
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '/tmp/neovim'
    depth: 1
  tags:
    - nvim

- name: Build and install Neovim
  become: true
  command:
    cmd: "{{ item }}"
    chdir: /tmp/neovim
  loop:
    - make CMAKE_BUILD_TYPE=RelWithDebInfo
    - make install
  tags:
    - nvim
