- name: Install stow 
  package:
    name: stow
    state: present  
  tags: stow

- name: Set XDG_CONFIG_HOME
  environment:
    XDG_CONFIG_HOME: "{{ ansible_env.HOME }}/.config"
  tags: stow

- name: Create directory for config file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/"
    state: directory
    mode: '0755'
  tags: stow

- name: Check if directory exists
  stat:
    path: "~/Personal/dotfiles/"
  register: repo_status
  tags: stow

- name: Clone dotfiles project
  git:
    repo: "https://github.com/Snaylaker/dotfiles"  
    dest: "{{ ansible_env.HOME }}/Personal/dotfiles"  
    version: main 
  become: true 
  tags: stow

- name: Run stow to manage configurations
  shell: stow -t {{ ansible_env.HOME }}/ . 
  become: true
  args:
    chdir: "{{ ansible_env.HOME }}/Personal/dotfiles"
  tags: stow
