- name: Install Tmux 
  package:
    name: tmux 
    state: present
  tags:
    - tmux 

- name: Append bindkey configuration to ~/.zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'bindkey -s ^f "tmux-sessionizer\n"'
    state: present
  tags:
    - tmux
    - zsh
