#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/work ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# Exit the script if no directory was selected
if [[ -z $selected ]]; then
    exit 0
fi

# Extract the directory name and replace '.' with '_' to form a session name
selected_name=$(basename "$selected" | tr . _)

# Check if a tmux session with the selected name already exists
if tmux has-session -t=$selected_name 2> /dev/null; then
    # If the session exists and we are not inside a tmux session, attach to it
    if [[ -z $TMUX ]]; then
        echo "Already inside a tmux session with name $selected_name"
        tmux attach-session -t $selected_name
        exit 0
    fi
else
    # If the session does not exist, create it
    echo "Creating new tmux session with name $selected_name"
    if [[ -z $TMUX ]]; then
        tmux new-session -s $selected_name -c $selected
    else
        tmux new-session -d -s $selected_name -c $selected
    fi
fi

# The following will only execute if we are already inside a tmux session
if [[ -n $TMUX ]]; then
    echo "switch to $selected_name"
    tmux switch-client -t $selected_name
fi
